replicaCount: 1

image: localhost:32000/askeladden:slim

labels:
  app: askeladden

selectorLabels:
  app: askeladden

deploymentLabels:
  env: staging

service:
  type: NodePort
  port: 80
  targetPort: 8090
  nodePort: 30009